### ISSUE TITLE
[Feature] Update activity settings

### ISSUE THREAD

**Issue by denniedegroot** [ThaYoung1/com.thayoung1.strava#11]
Thanks for you app!

I have a feature request, would it be possible to change activity settings?
For example: trigger on new activity -> if activity is walking/cycling and less then 20km -> then mute activity.

Basically I would like to create something like activityfix in Homey ;)
https://www.activityfix.com/

**Comment by ThaYoung1** [comment]
Hi Dennie,

I can look into that. Can you give me an example of where you can mute activities on the Strava dashboard? 

So not from the activityfix perspective, but from within Strava itself. With that info I can investigate some things and if possible (which most likely is because activityfix also does it) implement this in the Homey Strava App.

**Comment by ThaYoung1** [comment]
Clear, feature will be on the list for the next release

**Comment by denniedegroot** [comment]
Thanks so much!

**Comment by ThaYoung1** [comment]
New version just went live on the test track (https://homey.app/nl-nl/app/com.thayoung1.strava/Strava/test/). You can install this test version or wait for me to set it live on the production track. It contains the hide/show activity on timeline. By using logic variables in the AND section of the flow you can achieve your goal. If you need any explanation for this, let me know.

**Comment by denniedegroot** [comment]
Thanks! I just tested it but I am getting a authorization error. Do I need to remove and re-add the strava 'device' again?

[log] 2023-04-17 17:50:02 [ManagerDrivers] [Driver:stravauser] [Device:0bf46ad0-6689-4cac-bedd-39d3851fc21d] response: {"message":"Authorization Error","errors":[{"resource":"AccessToken","field":"activity:write_permission","code":"missing"}]}

**Comment by ThaYoung1** [comment]
Indeed, forgot to mention that. Due to new access rights you have to re-add the device. Good to hear it works
